### ISSUE TITLE
Pritotize what to do for the pre-release print:

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#56]
- [x] Full width code snippet #17 @kbjarkefur 
- [x] Errata #52 @bbdaniels 
- [x] Add abbreviaton page #54 @bbdaniels 
- [x] Stata Appendix #35 @kbjarkefur 
- [x] Planning data work code structure #53 @luizaandrade 
- [x] Mention Code review #57 @luizaandrade 
- [x] Text Maria and give her option to review if she wants

**Comment by kbjarkefur** [comment]
#35 is solved in #63
